# Generated by Django 5.2.9 on 2025-12-22 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('contacto', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField()),
                ('tipoSangue', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('peso', models.FloatField()),
                ('medicacao', models.BooleanField(default=False)),
                ('tatuagem', models.BooleanField(default=False)),
                ('piercing', models.BooleanField(default=False)),
                ('doente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('contacto', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('contacto', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangue', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantidade', models.FloatField()),
                ('componente', models.CharField(choices=[('GR', 'Glóbulos Vermelhos'), ('PL', 'Plasma'), ('PQ', 'Plaquetas')], max_length=2)),
                ('estadoPedido', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Rejeitado'), ('P', 'Pendente')], max_length=1)),
                ('dataPedido', models.DateField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='myBancoSangue.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.FloatField()),
                ('dador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doacoes', to='myBancoSangue.dador')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doacoes', to='myBancoSangue.posto')),
            ],
        ),
        migrations.CreateModel(
            name='StockSangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSangue', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('componente', models.CharField(choices=[('GR', 'Glóbulos Vermelhos'), ('PL', 'Plasma'), ('PQ', 'Plaquetas')], max_length=2)),
                ('quantidade', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('tipoSangue', 'componente')},
            },
        ),
    ]
