# Generated by Django 5.2.9 on 2025-12-23 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBancoSangue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('POSTO', 'Posto'), ('HOSPITAL', 'Hospital')], max_length=10)),
                ('hospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBancoSangue.hospital')),
                ('posto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBancoSangue.posto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
