# Generated by Django 5.2.9 on 2025-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBancoSangue', '0002_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
    ]
