# Generated by Django 5.2.9 on 2025-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBancoSangue', '0003_posto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksangue',
            name='limiteMaximo',
            field=models.FloatField(default=1000000000.0),
        ),
        migrations.AddField(
            model_name='stocksangue',
            name='limiteMinimo',
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name='pedidohospital',
            name='componente',
            field=models.CharField(choices=[('GV', 'Glóbulos Vermelhos'), ('PL', 'Plasma'), ('PQ', 'Plaquetas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stocksangue',
            name='componente',
            field=models.CharField(choices=[('GV', 'Glóbulos Vermelhos'), ('PL', 'Plasma'), ('PQ', 'Plaquetas')], max_length=2),
        ),
    ]
