# Generated by Django 5.2.9 on 2026-01-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBancoSangue', '0004_stocksangue_limitemaximo_stocksangue_limiteminimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dador',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='quantidade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='pedidohospital',
            name='quantidade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='stocksangue',
            name='limiteMaximo',
            field=models.FloatField(default=1000000000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='stocksangue',
            name='limiteMinimo',
            field=models.FloatField(default=200.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='stocksangue',
            name='quantidade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
